demo:
  service:
    version: 1.0.0

dubbo:
  registry:
    address: nacos://${NACOS_ADDR}?username=${NACOS_USERNAME}&password=${NACOS_PASSWORD}
    parameters:
      namespace: ${NACOS_NAMESPACE:a550735a03c3}
      group: ${NACOS_GROUP:DEFAULT_GROUP}
      username: ${NACOS_USERNAME}
      password: ${NACOS_PASSWORD}
      ignoreCheckKeys: username,password
  scan:
    base-packages: org.apache.dubbo.spring.boot.sample.provider.service
  protocol:
    port: 20880
    name: dubbo
  provider:
    parameters:
      paas-name: ${SERVICE_NAME:provider}
      paas-ns: ${PAAS_NS:apm}
      service-type: Dubbo
      username: ${NACOS_USERNAME}
      password: ${NACOS_PASSWORD}
      configs: ${NACOS_NAMESPACE}@${CONFIG_GROUP:DEFAULT_GROUP}@${SERVICE_NAME}-${PROFILE}
  application:
    name: ${SERVICE_NAME:provider}