spring:
  application:
    name: eureka-demo-provider
eureka:
  instance:
    prefer-ip-address: ${MESH_SWITCHER_MESH}
    ip-address: ${MESH_SVC_NAME}.${K8S_NAMESPACE}.svc.cluster.local
    hostname: eureka-demo-provider
    metadata-map:
      isjoin: ${MESH_SWITCHER_MESH} #是否加入网格 true/false
      deploy: ${DEPLOY_TYPE} #部署方式 container/vm
      svcname: ${K8S_NAMESPACE}:${MESH_SVC_NAME} #在k8s集群对应的服务
  client:
    register-with-eureka: true
    service-url.defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
