spring:
  application:
    name: zookeeper-dubbo-demo-provider
demo:
  service:
    version: 1.0.0
    group: zookeeper-dubbo

dubbo:
  protocol:
    port: 20880
    name: dubbo
  registry:
    address: zookeeper://${ZOOKEEPER_SERVER_URL}:${ZOOKEEPER_SERVER_PORT}
  provider:
    parameters:
      isjoin: ${MESH_SWITCHER_MESH}
      deploy: ${DEPLOY_TYPE}
      svcname: ${PAAS_NS}:${MESH_SVC_NAME}

