spring:
  application:
    name: zookeeper-dubbo-demo-consumer
services:
  hello:
    version: 1.0.0
    group: zookeeper-dubbo
  test:
    version: 1.0.0
    group: zookeeper-dubbo
dubbo:
  protocol:
    port: 20880
    name: dubbo
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    check: false
    parameters:
      isjoin: false
      deploy: container
      svcname: default:zookeeper-dubbo-demo-consume