spring:
  application:
    name: springcloud-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        metadata:
          isjoin: true
          deploy: container
          svcname: default:springcloud-provider
        username: nacos
        password: nacos