spring:
  application:
    name: eureka-consumer
eureka:
  instance:
    prefer-ip-address: ${MESH_SWITCHER_MESH}
    ip-address: ${MESH_SVC_NAME}.${PAAS_NS}.svc.cluster.local
    hostname: eureka-consumer
    metadata-map:
      isjoin: ${MESH_SWITCHER_MESH} #是否加入网格 true/false
      deploy: ${DEPLOY_TYPE} #部署方式 container/vm
      svcname: ${PAAS_NS}:${MESH_SVC_NAME} #在k8s集群对应的服务
  client:
    register-with-eureka: true
    service-url.defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
    fetch-registry: true
#设置超时60s，模拟故障模拟的延时
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000