spring:
  application:
    name: eureka-demo-provider
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
#    hostname: eureka-demo-provider
    metadata-map:
      isjoin: false
      deploy: container
      svcname: default:eureka-demo-provider
  client:
    register-with-eureka: true
    service-url.defaultZone: http://127.0.0.1:8761/eureka/
