spring:
  application:
    name: springcloud-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        metadata:
          isjoin: true
          deploy: vm
          svcname: default:springcloud-consumer
        username: nacos
        password: nacos

#模拟故障模拟，设置延时
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000